//
// Created by lmw on 12/05/16.
//

#ifndef ARDUINO_FLOTILLA_DUMMY_HANDLEUPDATE_H
#define ARDUINO_FLOTILLA_DUMMY_HANDLEUPDATE_H

void handleUpdate();

#endif  // ARDUINO_FLOTILLA_DUMMY_HANDLEUPDATE_H
